### ISSUE TITLE
Invalid SSL certificates are not allowed

### ISSUE THREAD

**Issue by Kernald** [itolianezzz/redmine#1]
Trying to access to a Redmine using a self-signed certificate, I got an error (unable to login on UI, logcat following):

```
09-09 18:55:40.475: E/Redmine.LoginActivity(5016): Error! Exception: 
09-09 18:55:40.475: E/Redmine.LoginActivity(5016): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.<init>(OpenSSLSocketImpl.java:647)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:618)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.commons.httpclient.HttpConnection.open(Unknown Source)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.commons.httpclient.HttpClient.executeMethod(Unknown Source)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.commons.httpclient.HttpClient.executeMethod(Unknown Source)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at ru.spb.itolia.redmine.api.RedmineApiManager.getApiKey(RedmineApiManager.java:65)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at ru.spb.itolia.redmine.ui.LoginActivity$LoginTask.doInBackground(LoginActivity.java:74)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at ru.spb.itolia.redmine.ui.LoginActivity$LoginTask.doInBackground(LoginActivity.java:1)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at android.os.AsyncTask$2.call(AsyncTask.java:287)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at java.util.concurrent.FutureTask.run(FutureTask.java:137)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at java.lang.Thread.run(Thread.java:856)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:192)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:597)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:395)
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  ... 16 more
09-09 18:55:40.475: E/Redmine.LoginActivity(5016): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
09-09 18:55:40.475: E/Redmine.LoginActivity(5016):  ... 21 more
09-09 18:55:40.475: W/System.err(5016): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
09-09 18:55:40.475: W/System.err(5016):     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398)
09-09 18:55:40.475: W/System.err(5016):     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.<init>(OpenSSLSocketImpl.java:647)
09-09 18:55:40.475: W/System.err(5016):     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:618)
09-09 18:55:40.475: W/System.err(5016):     at org.apache.commons.httpclient.HttpConnection.open(Unknown Source)
09-09 18:55:40.475: W/System.err(5016):     at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
09-09 18:55:40.475: W/System.err(5016):     at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
09-09 18:55:40.475: W/System.err(5016):     at org.apache.commons.httpclient.HttpClient.executeMethod(Unknown Source)
09-09 18:55:40.475: W/System.err(5016):     at org.apache.commons.httpclient.HttpClient.executeMethod(Unknown Source)
09-09 18:55:40.475: W/System.err(5016):     at ru.spb.itolia.redmine.api.RedmineApiManager.getApiKey(RedmineApiManager.java:65)
09-09 18:55:40.475: W/System.err(5016):     at ru.spb.itolia.redmine.ui.LoginActivity$LoginTask.doInBackground(LoginActivity.java:74)
09-09 18:55:40.475: W/System.err(5016):     at ru.spb.itolia.redmine.ui.LoginActivity$LoginTask.doInBackground(LoginActivity.java:1)
09-09 18:55:40.485: W/System.err(5016):     at android.os.AsyncTask$2.call(AsyncTask.java:287)
09-09 18:55:40.485: W/System.err(5016):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
09-09 18:55:40.485: W/System.err(5016):     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
09-09 18:55:40.485: W/System.err(5016):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
09-09 18:55:40.485: W/System.err(5016):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
09-09 18:55:40.485: W/System.err(5016):     at java.lang.Thread.run(Thread.java:856)
09-09 18:55:40.485: W/System.err(5016): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
09-09 18:55:40.485: W/System.err(5016):     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:192)
09-09 18:55:40.485: W/System.err(5016):     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
09-09 18:55:40.485: W/System.err(5016):     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:597)
09-09 18:55:40.485: W/System.err(5016):     at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
09-09 18:55:40.485: W/System.err(5016):     at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:395)
09-09 18:55:40.485: W/System.err(5016):     ... 16 more
09-09 18:55:40.485: W/System.err(5016): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
09-09 18:55:40.485: W/System.err(5016):     ... 21 more
```

For reference: http://stackoverflow.com/questions/1828775/how-to-handle-invalid-ssl-certificates-with-apache-httpclient

**Comment by itolianezzz** [comment]
Hi! Thanks for feedback. I'm just learning to make apps. This is my first one. So, there might be a lot of bugs yet. I'll try to fix this issue as soon as I have free time

**Comment by Kernald** [comment]
There's no problem, I'm just trying to help ;-) I'm not an experienced Android/Java developer neither.

**Comment by Kernald** [comment]
Maybe take a look at https://github.com/taskadapter/redmine-java-api, which is a library encapsulating all Redmine API calls.
